//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apisShopBridge.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using apisShopBridge.Models;
    using System.Data;
    
    public partial class dbShopBridgeInventoryEntities : DbContext,IAppContext
    {
        public dbShopBridgeInventoryEntities()
            : base("name=dbShopBridgeInventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public IDbSet<ItemList> ItemLists { get; set; }
        public void MarkAsModified(ItemList item)
        {
            Entry(item).State = EntityState.Modified;
        }
    }
}
